application: parabaypad
version: 1
runtime: python
api_version: 1

default_expiration: 1s  # This is good for images, which never change

inbound_services:
- mail
- xmpp_message

builtins:
- datastore_admin: on
- remote_api: on

handlers:

# Data uploader
- url: /_ah/xmpp/message/chat/
  script: controllers/xmpp.py
- url: /(transcript)/.*
  script: controllers/\1.py
- url: /(task)/.*
  script: controllers/\1.py
  login: admin

- url: /google/(.*)
  script: /services/googleservice.py
  login: required
  
- url: /shell/.*
  script: shell.py
  login: required
  
- url: /assets/(.*)
  script: /services/uploadservice.py
  
- url: /assets/(.*)/(.*)
  script: /services/uploadservice.py
  
- url: /assets/(.*)/(.*)/(.*)
  script: /services/uploadservice.py
  
- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)
  
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /static/(script.js|styles.css|upload.py)
  static_files: static/\1
  upload: static/(script.js|styles.css|upload.py)
  expiration: 1h  # Shorter expiration, these change often

- url: /static
  static_dir: static
- url: /static/login
  static_dir: static/login

- url: /googlee17f78eece841da6.html
  static_files: static/googlee17f78eece841da6.html
  upload: googlee17f78eece841da6.html
  
- url: /app/cache.manifest
  mime_type: text/cache-manifest
  static_files: static/app/cache.manifest
  upload: cache.manifest
  
- url: /app
  static_dir: static/app
   
- url: /load
  script: services/bulkloader.py
  
- url: /assetlist/.*
  script: services/assetlist.py
    
- url: /fbook.*
  script: facebookoauth.py
  
- url: /_ah/mail/.+ 
  script: services/incomingemailhandler.py 
  login: admin
          
- url: .*
  script: main.py
  login: required

skip_files:
- (closure\.*)
